name: Release

on:
  push:
    branches:
      - main

env:
  STORE_PATH: ""

jobs:
  release:
    if: ${{ github.repository_owner == 'lmsqueezy' }}
    name: "Create Release Pull Request or Publish to npm"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: Cache Bun dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.bun
            bun.lockb
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install

      - name: Build the package
        run: bun run build

      - name: Publish to NPM
        id: changesets
        uses: changesets/action@v1.4.5
        with:
          commit: "chore(release): version packages"
          title: "chore(release): version packages"
          version: node .github/changeset-version.js
          publish: npx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_ENV: "production"
