name: Release

on:
  push:
    branches:
      - main

env:
  STORE_PATH: ""

jobs:
  release:
    if: ${{ github.repository_owner == 'lmsqueezy' }}
    name: "Create Release Pull Request or Publish to npm"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build the package
        run: bun build

      - name: Publish to NPM
        id: changesets
        uses: changesets/action@v1.4.5
        with:
          commit: "chore(release): version packages"
          title: "chore(release): version packages"
          version: bun changeset version && bun install
          publish: bun changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_ENV: "production"
